name: Build and push docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.0.6

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rovnyart/telegram-bot-iamdrunk:${{ steps.extract_version.outputs.version }}

    - uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push docker image
      run: docker push rovnyart/telegram-bot-iamdrunk:${{ steps.extract_version.outputs.version }}
